function clarificationTestResponse() {
    return [
        {"FUNCTION":"Testing clarification picker..."},
        {
            "CLARIFY_WIDGET":1,
            "CLARIFY_QUESTION":"Which alarm should Buddy delete?",
            "CLARIFY_CONTEXT":"Delete one of the alarms at 07:00 or 07:30.",
            "CLARIFY_OPTION_COUNT":3,
            "CLARIFY_OPTION_0":"07:00",
            "CLARIFY_OPTION_1":"07:30",
            "CLARIFY_OPTION_2":"Cancel"
        },
        {"CHAT_DONE":true}
    ];
}

exports.specificResponses = {
    "This is just a test message": clarificationTestResponse(),
    "What's the weather like?": [{"FUNCTION":"Checking the weather nearby..."},{"WEATHER_WIDGET":2,"WEATHER_WIDGET_CURRENT_TEMP":12,"WEATHER_WIDGET_FEELS_LIKE":12,"WEATHER_WIDGET_LOCATION":"REDWOOD CITY","WEATHER_WIDGET_DAY_SUMMARY":"Fair","WEATHER_WIDGET_TEMP_UNIT":"°C","WEATHER_WIDGET_WIND_SPEED":1,"WEATHER_WIDGET_WIND_SPEED_UNIT":"mph","WEATHER_WIDGET_DAY_ICON":8},{"CHAT":"It's partly cloudy and"},{"CHAT":" "},{"CHAT":"12°C. "},{"CHAT":"The "},{"CHAT":"wind "},{"CHAT":"is "},{"CHAT":"1 "},{"CHAT":"mph "},{"CHAT":"from "},{"CHAT":"the "},{"CHAT":"NW."},{"CHAT_DONE":true}],
    "Set a baking timer for five minutes.": [{"FUNCTION":"Setting a timer"},{"SET_ALARM_TIME":300,"SET_ALARM_IS_TIMER":true,"SET_ALARM_NAME":"Baking"},{"CHAT":"OK"},{"CHAT":". "},{"CHAT":"I've "},{"CHAT":"set "},{"CHAT":"a "},{"CHAT":"timer "},{"CHAT":"for "},{"CHAT":"5 "},{"CHAT":"minutes "},{"CHAT":"called "},{"CHAT":"Baking.\n"},{"CHAT_DONE":true}],
    "Will I need an umbrella tomorrow?": [{"FUNCTION":"Checking the daily forecast nearby..."},{"WEATHER_WIDGET":1,"WEATHER_WIDGET_DAY_HIGH":19,"WEATHER_WIDGET_DAY_LOW":9,"WEATHER_WIDGET_LOCATION":"REDWOOD CITY","WEATHER_WIDGET_DAY_SUMMARY":"Partly Cloudy","WEATHER_WIDGET_TEMP_UNIT":"°C","WEATHER_WIDGET_DAY_ICON":7,"WEATHER_WIDGET_DAY_OF_WEEK":"Saturday"},{"CHAT":"Saturday"},{"CHAT":" "},{"CHAT":"will "},{"CHAT":"have "},{"CHAT":"times "},{"CHAT":"of "},{"CHAT":"sun "},{"CHAT":"and "},{"CHAT":"clouds, "},{"CHAT":"with "},{"CHAT":"a "},{"CHAT":"high "},{"CHAT":"of "},{"CHAT":"18 "},{"CHAT":"to "},{"CHAT":"20"},{"CHAT":"C "},{"CHAT":"and "},{"CHAT":"a "},{"CHAT":"low "},{"CHAT":"of "},{"CHAT":"8 "},{"CHAT":"to "},{"CHAT":"10C. "},{"CHAT":"There "},{"CHAT":"is "},{"CHAT":"no "},{"CHAT":"rain "},{"CHAT":"predicted, "},{"CHAT":"so "},{"CHAT":"you "},{"CHAT":"shouldn't "},{"CHAT":"need "},{"CHAT":"an "},{"CHAT":"umbrella.\n"},{"CHAT_DONE":true}],
    "At 5pm, remind me to go grocery shopping.": [{"FUNCTION":"Setting a reminder"},{"ACTION_REMINDER_WAS_SET":1745107200},{"CHAT":"OK. "},{"CHAT":"I'"},{"CHAT":"ll "},{"CHAT":"remind "},{"CHAT":"you "},{"CHAT":"to "},{"CHAT":"go "},{"CHAT":"grocery "},{"CHAT":"shopping "},{"CHAT":"at "},{"CHAT":"5pm.\n"},{"CHAT_DONE":true}],
    "Who was the 22nd president of the United States?": [{"HIGHLIGHT_WIDGET":1,"HIGHLIGHT_WIDGET_PRIMARY":"22","HIGHLIGHT_WIDGET_SECONDARY":"nd"},{"CHAT":"Grover Cleveland was the"},{"CHAT":" "},{"CHAT":"22nd "},{"CHAT":"president "},{"CHAT":"of "},{"CHAT":"the "},{"CHAT":"United "},{"CHAT":"States."},{"CHAT_DONE":true}],
    "Set an alarm for 11am.": [{"FUNCTION":"Setting an alarm"},{"SET_ALARM_TIME":1745085600,"SET_ALARM_IS_TIMER":false},{"CHAT":"OK. "},{"CHAT":"I'"},{"CHAT":"ve "},{"CHAT":"set "},{"CHAT":"an "},{"CHAT":"alarm "},{"CHAT":"for "},{"CHAT":"11:00 "},{"CHAT":"AM "},{"CHAT":"tomorrow.\n"},{"CHAT_DONE":true}],
    "What is 50 dollars in pounds?": [{"FUNCTION":"Checking the USD/GBP rate..."},{"HIGHLIGHT_WIDGET":1,"HIGHLIGHT_WIDGET_PRIMARY":"37.67","HIGHLIGHT_WIDGET_SECONDARY":"GBP"},{"CHAT_DONE":true}],
    "How do you say 'good morning' in German?": [{"CHAT":"That"},{"CHAT":" "},{"CHAT":"would "},{"CHAT":"be "},{"CHAT":"\"Guten "},{"CHAT":"Morgen\"."},{"CHAT_DONE":true}],
    "What is 47 squared?": [{"HIGHLIGHT_WIDGET":1,"HIGHLIGHT_WIDGET_PRIMARY":"2,209"},{"CHAT_DONE":true}],
    "What is the capital of Burkina Faso?": [{"CHAT":"The"},{"CHAT":" "},{"CHAT":"capital "},{"CHAT":"of "},{"CHAT":"Burkina "},{"CHAT":"Faso "},{"CHAT":"is "},{"CHAT":"Ouagadougou.\n"},{"CHAT_DONE":true}],
    "What is the population of Germany?": [{"FUNCTION":"Looking up \"Germany\"..."},{"HIGHLIGHT_WIDGET":1,"HIGHLIGHT_WIDGET_PRIMARY":"83.5","HIGHLIGHT_WIDGET_SECONDARY":"million people"},{"CHAT_DONE":true}],
}

exports.randomResponses = [
    [{"FUNCTION":"Looking up \"Pebble (watch)\"..."},{"CHAT":"The"},{"CHAT":" "},{"CHAT":"Pebble "},{"CHAT":"smartwatch "},{"CHAT":"was "},{"CHAT":"developed "},{"CHAT":"by "},{"CHAT":"Pebble "},{"CHAT":"Technology "},{"CHAT":"Corporation "},{"CHAT":"and "},{"CHAT":"shipped "},{"CHAT":"from "},{"CHAT":"2013"},{"CHAT":" "},{"CHAT":"to "},{"CHAT":"2016. "},{"CHAT":"In "},{"CHAT":"December "},{"CHAT":"2016, "},{"CHAT":"Pebble"},{"CHAT":" "},{"CHAT":"was "},{"CHAT":"sold "},{"CHAT":"to "},{"CHAT":"Fitbit, "},{"CHAT":"who "},{"CHAT":"were "},{"CHAT":"themselves "},{"CHAT":"acquired "},{"CHAT":"by "},{"CHAT":"Google "},{"CHAT":"in "},{"CHAT":"2021. "},{"CHAT":"In "},{"CHAT":"January "},{"CHAT":"2025, "},{"CHAT":"Google "},{"CHAT":"announced "},{"CHAT":"that "},{"CHAT":"the "},{"CHAT":"operating "},{"CHAT":"system "},{"CHAT":"Pebble "},{"CHAT":"smart"},{"CHAT":"watches "},{"CHAT":"use, "},{"CHAT":"PebbleOS, "},{"CHAT":"would "},{"CHAT":"be "},{"CHAT":"open-sourced. "},{"CHAT":"In "},{"CHAT":"March "},{"CHAT":"2025, "},{"CHAT":"it "},{"CHAT":"was "},{"CHAT":"announced "},{"CHAT":"that "},{"CHAT":"new "},{"CHAT":"devices "},{"CHAT":"would "},{"CHAT":"be "},{"CHAT":"produced "},{"CHAT":"using "},{"CHAT":"PebbleOS"},{"CHAT":" "},{"CHAT":"under "},{"CHAT":"the "},{"CHAT":"Core "},{"CHAT":"Devices "},{"CHAT":"brand "},{"CHAT":"name.\n"},{"CHAT_DONE":true}],
    [{"FUNCTION":"Checking the time in Honolulu"},{"FUNCTION":"Checking the time in Anchorage"},{"FUNCTION":"Checking the time in Los Angeles"},{"FUNCTION":"Checking the time in Denver"},{"FUNCTION":"Checking the time in Chicago"},{"FUNCTION":"Checking the time in New York"},{"CHAT":"Okay"},{"CHAT":", "},{"CHAT":"here "},{"CHAT":"are "},{"CHAT":"the "},{"CHAT":"times "},{"CHAT":"across "},{"CHAT":"the "},{"CHAT":"time "},{"CHAT":"zones "},{"CHAT":"of "},{"CHAT":"the "},{"CHAT":"United "},{"CHAT":"States: "},{"CHAT":"Honolulu "},{"CHAT":"is "},{"CHAT":"Fri"},{"CHAT":", "},{"CHAT":"18 "},{"CHAT":"Apr "},{"CHAT":"2025 "},{"CHAT":"19:42:"},{"CHAT":"08 "},{"CHAT":"HST; "},{"CHAT":"Anchorage "},{"CHAT":"is "},{"CHAT":"Fri, "},{"CHAT":"18 "},{"CHAT":"Apr "},{"CHAT":"2025 "},{"CHAT":"21:42:09 "},{"CHAT":"AKDT; "},{"CHAT":"Los "},{"CHAT":"Angeles "},{"CHAT":"is"},{"CHAT":" "},{"CHAT":"Fri, "},{"CHAT":"18 "},{"CHAT":"Apr "},{"CHAT":"2025 "},{"CHAT":"22:42:09 "},{"CHAT":"PDT; "},{"CHAT":"Denver "},{"CHAT":"is "},{"CHAT":"Fri, "},{"CHAT":"18 "},{"CHAT":"Apr "},{"CHAT":"2"},{"CHAT":"025 "},{"CHAT":"23:42:10 "},{"CHAT":"MDT; "},{"CHAT":"Chicago "},{"CHAT":"is "},{"CHAT":"Sat, "},{"CHAT":"19 "},{"CHAT":"Apr "},{"CHAT":"2025 "},{"CHAT":"00:42:10 "},{"CHAT":"CDT; "},{"CHAT":"and "},{"CHAT":"New "},{"CHAT":"York "},{"CHAT":"is "},{"CHAT":"Sat, "},{"CHAT":"19"},{"CHAT":" "},{"CHAT":"Apr "},{"CHAT":"2025 "},{"CHAT":"01:42:11 "},{"CHAT":"EDT.\n"},{"CHAT_DONE":true}],
    [{"FUNCTION":"Getting a calculator"},{"CHAT":"The"},{"CHAT":" "},{"CHAT":"circular "},{"CHAT":"screen "},{"CHAT":"has "},{"CHAT":"approximately "},{"CHAT":"25,446 "},{"CHAT":"pixels, "},{"CHAT":"while "},{"CHAT":"the "},{"CHAT":"rectangular"},{"CHAT":" "},{"CHAT":"screen "},{"CHAT":"has "},{"CHAT":"24,192 "},{"CHAT":"pixels.\n"},{"CHAT_DONE":true}],
    [{"FUNCTION":"Looking up \"Apple Inc.\"..."},{"CHAT":"Apple "},{"CHAT":"Inc. "},{"CHAT":"is"},{"CHAT":" "},{"CHAT":"headquartered "},{"CHAT":"in "},{"CHAT":"Cupertino, "},{"CHAT":"California, "},{"CHAT":"in "},{"CHAT":"Silicon "},{"CHAT":"Valley. "},{"CHAT":"It "},{"CHAT":"was "},{"CHAT":"founded "},{"CHAT":"in "},{"CHAT":"Los "},{"CHAT":"Altos, "},{"CHAT":"California."},{"CHAT_DONE":true}],
    [{"FUNCTION":"Getting a calculator"},{"HIGHLIGHT_WIDGET":1,"HIGHLIGHT_WIDGET_PRIMARY":"1,802,614,041,067","HIGHLIGHT_WIDGET_SECONDARY":"furlongs per fortnight"},{"CHAT_DONE":true}],
]
